title: EndeavourOS Development
logo: https://raw.githubusercontent.com/endeavouros-team/artwork-images-logo/master/icons/endeavouros-64x64.png
description: information about EndeavourOS Development.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  repository_url: https://github.com/endeavouros-team
